<?php

namespace PHPAlgorithmScaffold\Generator\File;

class UnitTest extends File
{
    /**
     * @inheritDoc
     */
    public function create(string $path, string $name): bool
    {
        $problemTestFile = new \Nette\PhpGenerator\PhpFile();
        $problemTestFile->addComment('Autogenerated test case file for problem ' . $name);
        $problemTestFile->addUse('PHPUnit\Framework\TestCase');
        $problemTestFile->addUse('LeetCode\Problems\\' . $name . '\\' . $name);
        file_put_contents($path . '/' . $name . 'Test.php', $problemTestFile);
        $class = new \Nette\PhpGenerator\ClassType($name . 'Test');
        $class->setExtends('TestCase')->setFinal();
        $class->addMethod('test' . $name . 'Example1');
        file_put_contents($path . '/' . $name . 'Test.php', $class, FILE_APPEND);
        return true;
    }
}
