<?php

/**
 * Autogenerated test case file for problem HelloWorld
 */

use LeetCode\Problems\HelloWorld\HelloWorld;
use PHPUnit\Framework\TestCase;
final class HelloWorldTest extends TestCase
{
	public function testHelloWorldExample1()
	{
	}
}
